# Generated by Django 4.1.5 on 2023-01-17 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0002_ticket_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="assigned_qa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tickets_as_qa",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
