# Generated by Django 4.1.5 on 2023-01-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_ticket_assigned_qa"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="qa_status",
            field=models.CharField(
                choices=[("PASS", "Pass"), ("FAIL", "Fail")],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
